library(vroom)
library(tidyverse)
african_countries <- c("Algeria", 
                       "Angola", 
                       "Benin", 
                       "Botswana", 
                       "Burkina Faso", 
                       "Burundi", 
                       "Cabo Verde", 
                       "Cameroon", 
                       "Central African Republic", 
                       "Chad", 
                       "Comoros", 
                       "Congo, Democratic Republic of the", 
                       "Congo, Republic of the", 
                       "Cote d'Ivoire", 
                       "Djibouti", 
                       "Egypt", 
                       "Equatorial Guinea", 
                       "Eritrea", 
                       "Eswatini", 
                       "Ethiopia", 
                       "Gabon", 
                       "Gambia", 
                       "Ghana", 
                       "Guinea", 
                       "Guinea-Bissau", 
                       "Kenya", 
                       "Lesotho", 
                       "Liberia", 
                       "Libya", 
                       "Madagascar", 
                       "Malawi", 
                       "Mali", 
                       "Mauritania", 
                       "Mauritius", 
                       "Morocco", 
                       "Mozambique", 
                       "Namibia", 
                       "Niger", 
                       "Nigeria", 
                       "Rwanda", 
                       "Sao Tome and Principe", 
                       "Senegal", 
                       "Seychelles", 
                       "Sierra Leone", 
                       "Somalia", 
                       "South Africa", 
                       "South Sudan", 
                       "Sudan", 
                       "Tanzania", 
                       "Togo", 
                       "Tunisia", 
                       "Uganda", 
                       "Zambia", 
                       "Zimbabwe")

european_countries <- c("Albania",
                        "Andorra",
                        "Armenia",
                        "Austria",
                        "Azerbaijan",
                        "Belarus",
                        "Belgium",
                        "Bosnia and Herzegovina",
                        "Bulgaria",
                        "Croatia",
                        "Cyprus",
                        "Czechia",
                        "Denmark",
                        "Estonia",
                        "Finland",
                        "France",
                        "Georgia",
                        "Germany",
                        "Greece",
                        "Hungary",
                        "Iceland",
                        "Ireland",
                        "Italy",
                        "Kazakhstan",
                        "Kosovo",
                        "Latvia",
                        "Liechtenstein",
                        "Lithuania",
                        "Luxembourg",
                        "Malta",
                        "Moldova",
                        "Monaco",
                        "Montenegro",
                        "Netherlands",
                        "North Macedonia",
                        "Norway",
                        "Poland",
                        "Portugal",
                        "Romania",
                        "Russia",
                        "San Marino",
                        "Serbia",
                        "Slovakia",
                        "Slovenia",
                        "Spain",
                        "Sweden",
                        "Switzerland",
                        "Turkey",
                        "Ukraine",
                        "United Kingdom",
                        "Vatican City")

asian_countries <- c("Afghanistan",
                     "Armenia",
                     "Azerbaijan",
                     "Bahrain",
                     "Bangladesh",
                     "Bhutan",
                     "Brunei",
                     "Cambodia",
                     "China",
                     "Cyprus",
                     "Georgia",
                     "India",
                     "Indonesia",
                     "Iran",
                     "Iraq",
                     "Israel",
                     "Japan",
                     "Jordan",
                     "Kazakhstan",
                     "Kuwait",
                     "Kyrgyzstan",
                     "Laos",
                     "Lebanon",
                     "Malaysia",
                     "Maldives",
                     "Mongolia",
                     "Myanmar",
                     "Nepal",
                     "North Korea",
                     "Oman",
                     "Pakistan",
                     "Palestine",
                     "Philippines",
                     "Qatar",
                     "Russia",
                     "Saudi Arabia",
                     "Singapore",
                     "South Korea",
                     "Sri Lanka",
                     "Syria",
                     "Taiwan",
                     "Tajikistan",
                     "Thailand",
                     "Timor-Leste",
                     "Turkey",
                     "Turkmenistan",
                     "United Arab Emirates",
                     "Uzbekistan",
                     "Vietnam",
                     "Yemen")

all_eurasia <- c(african_countries, asian_countries, european_countries)


# filter for african countries
in_df <- vroom(file = '/Volumes/oxford_ssd/data/taxalogue/taxalogue-1.0.0/downloads/BOLD_Public.01-Jan-2024.tsv') %>%
  filter(country %in% african_countries)


write_tsv(in_df,
          file = '/Volumes/oxford_ssd/data/taxalogue/taxalogue-1.0.0/downloads/BOLD_Public.01-Jan-2024_africa.tsv')


rm(in_df)
# filter for all eurasian countries
eurasia_df <- vroom(file = '/Volumes/oxford_ssd/data/taxalogue/taxalogue-1.0.0/downloads/BOLD_Public.01-Jan-2024.tsv') %>%
  filter(country %in% all_eurasia)


write_tsv(eurasia_df,
          file = '/Volumes/oxford_ssd/data/taxalogue/taxalogue-1.0.0/downloads/BOLD_Public.01-Jan-2024_eurasia.tsv')
